### PR TITLE
Use rails secrets for user names and passwords

### PR DESCRIPTION
**Pull request by acozine**
@dunn please test this much, I will look at the postgres and fedora changes next

### CODE REVIEW

**Comment by acozine** [comment]
At this point the playbook succeeds and secrets.yml looks good. I'm testing ingest, search, etc. on the resulting machine.

**Comment by acozine** [comment]
For this approach to work, you must execute the services role BEFORE the hydra-stack role. Updating local playbooks.

**Comment by dunn** [comment]
Sorry, I'm just getting to this now, but if you're confident it works then don't wait for me.

**Comment by acozine** [comment]
The script works but the resulting server is not working. So it needs refinement. I'd appreciate testing in parallel if you have bandwidth.

**Comment by dunn** [comment]
Gotcha.  Building a Vagrant instance now.

**Comment by acozine** [comment]
I found and fixed one mistake - apache runs now and I can log in - now for a test ingest

**Comment by acozine** [comment]
Connected to https://github.com/curationexperts/alexandria-v2/pull/576 - will open an issue for writing the ezid host and port to application.yml so we won't have an ezid.yml any more.

**Comment by dunn** [comment]
> will open an issue for writing the ezid host and port to application.yml so we won't have an ezid.yml any more

I added a commit doing that to the existing PR!

**Comment by acozine** [comment]
Yes, you did that in the alexandria codebase. It also needs to be done here in the ansible scripts, so when we build machines we put the host and port config in the right place.

**Pull request merged**
